import type { TProductoLevantamientoModel } from "../types/TProductoLevantamientoModel";

const dataLevantamiento = <TProductoLevantamientoModel[]>[
	{
		codigo: "001",
		nombre: "Taladro Percutor",
		codigoBarras: ["789012", "345678"],
		modelo: "XPT-900",
		categoria: "Herramientas Eléctricas",
		marca: "Bosch",
		precioVenta: 1999,
		stockTotal: 15,
		estadoAgregado: false,
	},
	{
		codigo: "002",
		nombre: "Destornillador Phillips",
		codigoBarras: ["123789", "654321"],
		modelo: "DP-15",
		categoria: "Herramientas Manuales",
		marca: "Stanley",
		precioVenta: 120,
		stockTotal: 50,
		estadoAgregado: false,
	},
	{
		codigo: "003",
		nombre: "Llave Inglesa",
		codigoBarras: ["987654", "321456"],
		modelo: "LI-10",
		categoria: "Herramientas Manuales",
		marca: "Truper",
		precioVenta: 350,
		stockTotal: 30,
		estadoAgregado: false,
	},
	{
		codigo: "004",
		nombre: "Sierra Circular",
		codigoBarras: ["456123", "789654"],
		modelo: "SC-700",
		categoria: "Herramientas Eléctricas",
		marca: "Makita",
		precioVenta: 2590,
		stockTotal: 10,
		estadoAgregado: false,
	},
	{
		codigo: "005",
		nombre: "Lija de Agua",
		codigoBarras: ["321789", "654987"],
		modelo: "LA-1000",
		categoria: "Abrasivos",
		marca: "3M",
		precioVenta: 30,
		stockTotal: 200,
		estadoAgregado: false,
	},
	{
		codigo: "006",
		nombre: "Clavos de Acero",
		codigoBarras: ["123456", "987123"],
		modelo: "CA-50",
		categoria: "Fijaciones",
		marca: "Fischer",
		precioVenta: 45,
		stockTotal: 1000,
		estadoAgregado: false,
	},
	{
		codigo: "007",
		nombre: "Cinta Métrica",
		codigoBarras: ["654321", "321654"],
		modelo: "CM-5M",
		categoria: "Instrumentos de Medición",
		marca: "Stanley",
		precioVenta: 75,
		stockTotal: 60,
		estadoAgregado: false,
	},
	{
		codigo: "008",
		nombre: "Alicate de Corte",
		codigoBarras: ["987123", "456789"],
		modelo: "AC-8",
		categoria: "Herramientas Manuales",
		marca: "Truper",
		precioVenta: 180,
		stockTotal: 40,
		estadoAgregado: false,
	},
	{
		codigo: "009",
		nombre: "Mascarilla de Protección",
		codigoBarras: ["123789", "654987"],
		modelo: "MP-95",
		categoria: "Seguridad Industrial",
		marca: "3M",
		precioVenta: 50,
		stockTotal: 500,
		estadoAgregado: false,
	},
	{
		codigo: "010",
		nombre: "Cutter Profesional",
		codigoBarras: ["456321", "789123"],
		modelo: "CP-10",
		categoria: "Herramientas Manuales",
		marca: "Olfa",
		precioVenta: 90,
		stockTotal: 80,
		estadoAgregado: false,
	},
	{
		codigo: "011",
		nombre: "Llave de Tubo",
		codigoBarras: ["321456", "654123"],
		modelo: "LT-14",
		categoria: "Herramientas Manuales",
		marca: "Stanley",
		precioVenta: 400,
		stockTotal: 25,
		estadoAgregado: false,
	},
	{
		codigo: "012",
		nombre: "Escalera de Aluminio",
		codigoBarras: ["987321", "123654"],
		modelo: "EA-8",
		categoria: "Equipos de Elevación",
		marca: "Werner",
		precioVenta: 1800,
		stockTotal: 8,
		estadoAgregado: false,
	},
	{
		codigo: "013",
		nombre: "Broca de Concreto",
		codigoBarras: ["456987", "321789"],
		modelo: "BC-6",
		categoria: "Accesorios de Herramientas",
		marca: "Bosch",
		precioVenta: 60,
		stockTotal: 120,
		estadoAgregado: false,
	},
	{
		codigo: "014",
		nombre: "Cerradura de Seguridad",
		codigoBarras: ["654789", "123456"],
		modelo: "CS-900",
		categoria: "Cerrajería",
		marca: "Yale",
		precioVenta: 750,
		stockTotal: 15,
		estadoAgregado: false,
	},
	{
		codigo: "015",
		nombre: "Pintura Esmalte",
		codigoBarras: ["789654", "456123"],
		modelo: "PE-100",
		categoria: "Pinturas y Recubrimientos",
		marca: "Sherwin Williams",
		precioVenta: 550,
		stockTotal: 30,
		estadoAgregado: false,
	},
];

export { dataLevantamiento };
